services:
  # Backend API Service
  - type: web
    name: capigrid-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: capigrid-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: REPL_ID
        sync: false
      - key: REPLIT_DOMAINS
        sync: false

databases:
  - name: capigrid-db
    databaseName: capigrid
    user: capigrid_user
    plan: starter
